<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolMgmt.Application\SchoolMgmt.Application.csproj" />
    <ProjectReference Include="..\SchoolMgmt.Infrastructure\SchoolMgmt.Infrastructure.csproj" />
    <ProjectReference Include="..\SchoolMgmt.Domain\SchoolMgmt.Domain.csproj" />
  </ItemGroup>

</Project>
